name: NATUWA
favicon: null
layout_spectrum: 0.75672
typography_spectrum: 0.06536
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Lugar de refugio y protecci√≥n.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f1d0f'
    - '#2c461b'
    - '#ae9d84'
    - '#cd8245'
    - '#668022'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
